/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mobiarch.jcsv;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    public static void print(ByteBuffer buff) {
        if (buff == null) {
            System.out.println("null");

            return;
        }

        //Dump bytes
        for (int i = 0; i < buff.limit(); ++i) {
            System.out.write((int) buff.get(i));
        }
    }

    @Test 
    public void basicUsage() {
        var str =
            "aa,bb,\"AA, BB\"  ,dd\r\n" +
            "ee,ff,gg,hh,ii,jj\r\n";
        var data = ByteBuffer.wrap(str.getBytes(StandardCharsets.UTF_8));

        Parser p = new Parser();
        
        p.parse(data, 10, record -> {
            assertTrue(record.lineIndex() < 2);

            if (record.lineIndex() == 0) {
                assertEquals(record.field(2).limit(), 6);
            } else if (record.lineIndex() == 1) {
                assertEquals(record.numFields(), 6);
            } else {
                fail("Invalid row index");
            }
        });
    }
}
