/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mobiarch.jcsv;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Parser classUnderTest = new Parser();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
